GET http://localhost:8080/api/genres

###
GET http://localhost:8080/api/genres/123

###
GET http://localhost:8080/api/genres/6195207c785ee4affdff4279

###
POST http://localhost:8080/api/genres
Content-Type: application/json
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MWEzZjNiMDhiYTNjMGQwODhlYjM2MDAiLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE2Mzk5MzAwNjl9.t5Sodnnv6RCci-1hsJXfErNRgNK4D4fkayZioODNWdc

{
  "name": "Sci-fi"
}

###
POST http://localhost:8080/api/genres
Content-Type: application/json
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MWEzZjNiMDhiYTNjMGQwODhlYjM2MDAiLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE2Mzk5MzAwNjl9.t5Sodnnv6RCci-1hsJXfErNRgNK4D4fkayZioODNWdc

{
  "name": "Thriller"
}

###
POST http://localhost:8080/api/genres
Content-Type: application/json
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MWEzZjNiMDhiYTNjMGQwODhlYjM2MDAiLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE2Mzk5MzAwNjl9.t5Sodnnv6RCci-1hsJXfErNRgNK4D4fkayZioODNWdc

{
  "name": "Action"
}

###
POST http://localhost:8080/api/genres
Content-Type: application/json
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MWE0MjEzNTJhMGIxMjU4ZDExZmFhNDEiLCJpYXQiOjE2MzgxNDYzNTd9._kpjQoIbE1dF6cTPiJoUCrBlqLRL6zillXNZI0-k9G8

{
  "name": "@"
}

###
POST http://localhost:8080/api/genres
Content-Type: application/json
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MWE0MjEzNTJhMGIxMjU4ZDExZmFhNDEiLCJpYXQiOjE2MzgxNDYzNTd9._kpjQoIbE1dF6cTPiJoUCrBlqLRL6zillXNZI0-k9G8

{
  "name": "Horror"
}

###
PUT http://localhost:8080/api/genres/61927d419653f511cbfaae9f
Content-Type: application/json

{
  "name": "Comedy"
}

###
DELETE http://localhost:8080/api/genres/61a421952a0b1258d11faa45
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MWEzZjNiMDhiYTNjMGQwODhlYjM2MDAiLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE2MzgyMTA0MDR9.Et2k0Ut6iAmVo4RWmzZ7YCsr0OWHYFNsgYzO7iA1YQA
